### ISSUE TITLE
パーサ TODO

### ISSUE THREAD

**Issue by oshamashama** [sylms/csv2sql#2]
- [x] 指導教員 https://github.com/sylms/csv2sql/blob/e3f155dee8d884b6c586f75ce0c596283c78fb66/main.go#L314
- [ ]  https://github.com/sylms/csv2sql/blob/e3f155dee8d884b6c586f75ce0c596283c78fb66/main.go#L391
- [x] 標準履修年次 https://github.com/sylms/csv2sql/blob/e3f155dee8d884b6c586f75ce0c596283c78fb66/main.go#L428
- [x] 曜時 https://github.com/sylms/csv2sql/blob/e3f155dee8d884b6c586f75ce0c596283c78fb66/main.go#L451
